/**
 * What the RBFS tool shows: the run (RBFS plus A* tree search on the same
 * problem, recomputed when the problem changes, not per step), the recursion
 * tree at a step (the open calls and their successors, as Russell & Norvig
 * draw Figure 3.27), the state-graph highlight, and the counts so far.
 */
import type { GraphHighlight } from '$lib/components/search/legend';
import {
	checkHeuristic,
	graphProblem,
	shortestPath,
	type GraphProblemSpec,
	type HeuristicReport
} from '$lib/theory/graphs';
import { search, type SearchResult } from '$lib/theory/search';
import {
	applyRbfsStep,
	rbfs,
	stackAt,
	type RbfsFrame,
	type RbfsResult,
	type RbfsStep
} from '$lib/theory/search/rbfs';

/** Nodes generated before the A* comparison run stops (tree search can grow fast). */
export const ASTAR_NODE_LIMIT = 50_000;

export interface RbfsRun {
	spec: GraphProblemSpec;
	result: RbfsResult;
	/** A* tree search on the same problem (no step trace). */
	astar: SearchResult;
	/** A cheapest path from the start to a goal, or null when none is reachable. */
	best: { cost: number; states: string[] } | null;
	heuristic: HeuristicReport;
}

/** Runs RBFS and A* tree search on a graph problem (alphabetical successors, §3.4). */
export function runRbfs(spec: GraphProblemSpec, maxExpansions: number): RbfsRun {
	const problem = graphProblem(spec);
	return {
		spec,
		result: rbfs(problem, { maxExpansions }),
		astar: search(problem, {
			strategy: 'astar',
			mode: 'tree',
			maxExpansions,
			maxNodes: ASTAR_NODE_LIMIT,
			record: 'summary'
		}),
		best: shortestPath(spec),
		heuristic: checkHeuristic(spec)
	};
}

export interface ProblemFacts {
	start: string;
	goals: string[];
	states: number;
	edges: number;
	directed: boolean;
	hCount: number;
	hText: string;
}

export function problemFacts(spec: GraphProblemSpec): ProblemFacts {
	const hCount = spec.h ? Object.keys(spec.h).length : 0;
	const label = spec.hLabel?.trim();
	return {
		start: spec.start,
		goals: spec.goals,
		states: spec.graph.nodes.length,
		edges: spec.graph.edges.length,
		directed: spec.graph.directed,
		hCount,
		hText: label
			? label
			: hCount
				? `Given for ${hCount} of ${spec.graph.nodes.length} states`
				: 'None (h = 0 for every state)'
	};
}

// ---------------------------------------------------------------------------
// The recursion tree at a step
// ---------------------------------------------------------------------------

/**
 * - `current`: the node of the call that runs the step;
 * - `open`: the node of another open call (on the recursion path);
 * - `stored`: a successor kept in memory, not on the path;
 * - `forgotten`: a successor dropped as its call returns (shown at that step only);
 * - `goal`: the goal node that was found.
 */
export type TreeStatus = 'current' | 'open' | 'stored' | 'forgotten' | 'goal';

/** What the step did with a node: picked it as best or alternative, or found it over the limit. */
export type TreeRole = 'best' | 'alternative' | 'exceeds' | null;

export interface TreeViewNode {
	id: number;
	parent: number | null;
	label: string;
	key: string;
	g: number;
	h: number;
	/** Current f. */
	f: number;
	/** The f this step replaced by a backed-up value (return and dead-end steps), else null. */
	previousF: number | null;
	/** f came back from a forgotten subtree (it is above the f the node was generated with). */
	backedUp: boolean;
	/** f was raised to the parent's f when generated: max(g + h, f(parent)) > g + h. */
	inherited: boolean;
	/** f_limit of the node's call while it is open (or returning at this step), else null. */
	limit: number | null;
	status: TreeStatus;
	role: TreeRole;
	/** Generated by this step. */
	isNew: boolean;
	/** On the solution path (goal step). */
	onSolution: boolean;
}

export interface TreeView {
	/** Root first; each node's children in successor order. */
	nodes: TreeViewNode[];
	current: number | null;
	/** Nodes of the open calls after the step, root first (at a goal step, the solution path). */
	path: number[];
}

function cloneFrames(frames: readonly RbfsFrame[]): RbfsFrame[] {
	return frames.map((fr) => ({ ...fr, successors: fr.successors.map((e) => ({ ...e })) }));
}

/** The recursion tree after step `index` (a return step also shows what it forgets). */
export function treeAt(result: RbfsResult, index: number): TreeView {
	if (result.nodes.length === 0) return { nodes: [], current: null, path: [] };
	const step: RbfsStep | undefined = result.steps[index];
	const before = stackAt(result, index - 1);
	const after = cloneFrames(before);
	if (step) applyRbfsStep(result, after, step);

	const current = step ? step.node : 0;
	const returning = step && (step.kind === 'return' || step.kind === 'dead-end');
	const out: TreeViewNode[] = [];
	const byId = new Map<number, TreeViewNode>();
	const solution = step?.kind === 'goal' ? new Set(after.map((fr) => fr.node)) : new Set<number>();

	const add = (id: number, f: number, status: TreeStatus) => {
		const n = result.nodes[id];
		const node: TreeViewNode = {
			id,
			parent: n.parent,
			label: n.label,
			key: n.key,
			g: n.g,
			h: n.h,
			f,
			previousF: null,
			backedUp: f > n.f,
			inherited: n.f > n.g + n.h,
			limit: null,
			status,
			role: null,
			isNew: step?.kind === 'expand' && n.parent === step.node && n.created === index,
			onSolution: solution.has(id)
		};
		out.push(node);
		byId.set(id, node);
		return node;
	};

	// The frames that make up the tree: after the step, or before it when the
	// root's own call returns (nothing is open afterwards).
	const frames = after.length ? after : returning ? before : [];
	if (frames.length === 0) {
		const root = add(0, result.nodes[0].f, 'current');
		return { nodes: [root], current: root.id, path: [] };
	}
	add(frames[0].node, result.nodes[frames[0].node].f, 'open');
	for (const fr of frames) for (const e of fr.successors) add(e.id, e.f, 'stored');
	for (const fr of after) {
		const node = byId.get(fr.node);
		if (node) {
			node.status = 'open';
			node.limit = fr.fLimit;
		}
	}

	if (step && returning) {
		const node = byId.get(step.node);
		const top = before[before.length - 1];
		if (node) {
			node.limit = step.fLimit;
			node.previousF = step.previous;
			if (after.length) {
				// Its successors are forgotten as the call returns.
				for (const e of top.successors) {
					const child = add(e.id, e.f, 'forgotten');
					if (step.kind === 'return' && e.id === step.best) child.role = 'exceeds';
				}
			} else if (step.kind === 'return') {
				for (const e of top.successors) {
					const child = byId.get(e.id);
					if (child) child.status = 'forgotten';
					if (child && e.id === step.best) child.role = 'exceeds';
				}
			}
		}
	}
	if (step?.kind === 'call') {
		const best = byId.get(step.best);
		if (best) best.role = 'best';
		const alt = step.alternative === null ? undefined : byId.get(step.alternative);
		if (alt) alt.role = 'alternative';
	}

	const cur = byId.get(current);
	if (cur) cur.status = step?.kind === 'goal' ? 'goal' : 'current';

	return { nodes: out, current: cur ? cur.id : null, path: after.map((fr) => fr.node) };
}

/**
 * The state graph's highlight at a step: the current call, the recursion path
 * down to it (the graph draws the path over the current state, so the path
 * stops before it), and the stored successors. At a goal step: the solution path.
 */
export function graphHighlightAt(view: TreeView): GraphHighlight {
	const byId = new Map(view.nodes.map((n) => [n.id, n]));
	const keys = (ids: readonly number[]) => ids.map((id) => byId.get(id)!.key);
	const frontier = [...new Set(view.nodes.filter((n) => n.status === 'stored').map((n) => n.key))];
	if (view.nodes.some((n) => n.status === 'goal')) return { path: keys(view.path), frontier };
	const at = view.current === null ? -1 : view.path.indexOf(view.current);
	const current = view.current === null ? undefined : byId.get(view.current)?.key;
	return { current, path: keys(at < 0 ? view.path : view.path.slice(0, at)), frontier };
}

// ---------------------------------------------------------------------------
// Counts so far
// ---------------------------------------------------------------------------

export interface Progress {
	expanded: number;
	reexpanded: number;
	generated: number;
	regenerated: number;
	/** Nodes kept in memory after the step. */
	stored: number;
	/** Most nodes kept at once up to this step. */
	maxStored: number;
	/** Depth of the node of the call that runs the step. */
	depth: number;
	/** Deepest call up to this step. */
	maxDepth: number;
}

/** Counts after step `index`; before the first step (or with no trace), the root alone. */
export function progressAt(result: RbfsResult, index: number): Progress {
	const zero: Progress = {
		expanded: 0,
		reexpanded: 0,
		generated: result.nodes.length ? 1 : 0,
		regenerated: 0,
		stored: result.nodes.length ? 1 : 0,
		maxStored: result.nodes.length ? 1 : 0,
		depth: 0,
		maxDepth: 0
	};
	const last = Math.min(index, result.steps.length - 1);
	if (last < 0) return zero;
	let maxStored = zero.maxStored;
	let maxDepth = 0;
	for (let i = 0; i <= last; i++) {
		const s = result.steps[i];
		maxStored = Math.max(maxStored, s.counts.stored);
		maxDepth = Math.max(maxDepth, result.nodes[s.node].depth);
	}
	const step = result.steps[last];
	return {
		...step.counts,
		maxStored,
		depth: result.nodes[step.node].depth,
		maxDepth
	};
}
