/**
 * Properties of the search strategies ("Review: Uninformed search
 * strategies", Uninformed Search slide 45; "All search strategies", Informed
 * Search slide 42) and the node counts behind their complexity classes.
 */
import type { Citation } from '$lib/lectures';
import type { StrategyId } from './types';

export interface StrategyProperties {
	strategy: Extract<StrategyId, 'bfs' | 'dfs' | 'ids' | 'ucs' | 'greedy' | 'astar'>;
	/** Row label as on the slide. */
	name: string;
	complete: string;
	optimal: string;
	time: string;
	space: string;
	/** Qualifications from the per-strategy "Properties of …" slides. */
	notes: string[];
	cite: Citation[];
}

/** The rows of the slide 42 table, in slide order. Complexities use Unicode superscripts. */
export const STRATEGY_PROPERTIES: readonly StrategyProperties[] = [
	{
		strategy: 'bfs',
		name: 'BFS',
		complete: 'Yes',
		optimal: 'If all step costs are equal',
		time: 'O(bᵈ)',
		space: 'O(bᵈ)',
		notes: [
			'Complete if the branching factor b is finite.',
			'Optimal if cost = 1 per step.',
			'Space is the bigger problem (more than time).'
		],
		cite: [
			{ deck: 'uninformed', slide: 31 },
			{ deck: 'uninformed', slide: 45 }
		]
	},
	{
		strategy: 'dfs',
		name: 'DFS',
		complete: 'No',
		optimal: 'No',
		time: 'O(bᵐ)',
		space: 'O(bm)',
		notes: [
			'Fails in infinite-depth spaces and spaces with loops; avoiding repeated states along the path makes it complete in finite spaces.',
			'Returns the first solution it finds.',
			'Terrible if m is much larger than d, but may be much faster than BFS when there are many solutions.',
			'Linear space.'
		],
		cite: [
			{ deck: 'uninformed', slide: 32 },
			{ deck: 'uninformed', slide: 45 }
		]
	},
	{
		strategy: 'ids',
		name: 'IDS',
		complete: 'Yes',
		optimal: 'If all step costs are equal',
		time: 'O(bᵈ)',
		space: 'O(bd)',
		notes: ['Nodes generated: (d+1)b⁰ + d b¹ + (d−1)b² + … + bᵈ = O(bᵈ).'],
		cite: [
			{ deck: 'uninformed', slide: 38 },
			{ deck: 'uninformed', slide: 45 }
		]
	},
	{
		strategy: 'ucs',
		name: 'UCS',
		complete: 'Yes',
		optimal: 'Yes',
		time: 'Number of nodes with g(n) ≤ C*',
		space: 'Number of nodes with g(n) ≤ C*',
		notes: [
			'Complete if every step cost is greater than some positive constant ε.',
			'Nodes are expanded in increasing order of path cost.',
			'O(b^(C*/ε)), which can be greater than O(bᵈ): the search can explore long paths of small steps before shorter paths of larger steps.'
		],
		cite: [
			{ deck: 'uninformed', slide: 44 },
			{ deck: 'uninformed', slide: 45 }
		]
	},
	{
		strategy: 'greedy',
		name: 'Greedy',
		complete: 'No',
		optimal: 'No',
		time: 'Worst case: O(bᵐ); best case: O(bd)',
		space: 'Worst case: O(bᵐ); best case: O(bd)',
		notes: ['Can get stuck in loops.', 'Can be much better with a good heuristic.'],
		cite: [
			{ deck: 'informed', slide: 14 },
			{ deck: 'informed', slide: 42 }
		]
	},
	{
		strategy: 'astar',
		name: 'A*',
		complete: 'Yes',
		optimal: 'Yes (if heuristic is admissible)',
		time: 'Number of nodes with g(n) + h(n) ≤ C*',
		space: 'Number of nodes with g(n) + h(n) ≤ C*',
		notes: [
			'Complete unless there are infinitely many nodes with f(n) ≤ C*.',
			'Tree search is optimal with an admissible heuristic; graph search needs a consistent one.',
			'Optimally efficient: no other tree-based algorithm with the same heuristic expands fewer nodes and is still guaranteed to find the optimal solution.'
		],
		cite: [
			{ deck: 'informed', slide: 29 },
			{ deck: 'informed', slide: 30 },
			{ deck: 'informed', slide: 31 },
			{ deck: 'informed', slide: 42 }
		]
	}
];

/** Symbols used in the table (Uninformed Search slides 30 and 45). */
export const COMPLEXITY_SYMBOLS: readonly { symbol: string; meaning: string }[] = [
	{ symbol: 'b', meaning: 'maximum branching factor of the search tree' },
	{ symbol: 'd', meaning: 'depth of the optimal solution' },
	{ symbol: 'm', meaning: 'maximum length of any path in the state space (may be infinite)' },
	{ symbol: 'C*', meaning: 'cost of the optimal solution' },
	{ symbol: 'g(n)', meaning: 'cost of the path from the start state to node n' }
];

function checkCount(name: string, value: number): bigint {
	if (!Number.isInteger(value) || value < 0) {
		throw new RangeError(`${name} must be a non-negative integer`);
	}
	return BigInt(value);
}

/** Nodes in a b-ary tree of depth d: 1 + b + b² + … + bᵈ. */
export function treeNodes(b: number, d: number): bigint {
	const bb = checkCount('b', b);
	const dd = checkCount('d', d);
	let total = 0n;
	let level = 1n;
	for (let i = 0n; i <= dd; i++) {
		total += level;
		level *= bb;
	}
	return total;
}

/** Nodes generated by IDS on a b-ary tree with the goal at depth d: (d+1)b⁰ + d b¹ + … + 1·bᵈ. */
export function idsNodes(b: number, d: number): bigint {
	const bb = checkCount('b', b);
	const dd = checkCount('d', d);
	let total = 0n;
	let level = 1n;
	for (let i = 0n; i <= dd; i++) {
		total += (dd + 1n - i) * level;
		level *= bb;
	}
	return total;
}

/**
 * Largest number of nodes DFS keeps in memory on a b-ary tree of depth m: the
 * unexpanded siblings along one path, b·m, plus the root.
 */
export function dfsSpace(b: number, m: number): bigint {
	return checkCount('b', b) * checkCount('m', m) + 1n;
}

/** Moves in the shortest Towers of Hanoi solution with n disks: 2ⁿ − 1 (Informed Search, slide 43). */
export function hanoiMoves(n: number): bigint {
	return (1n << checkCount('n', n)) - 1n;
}

/** Typical 8-puzzle search costs, average nodes expanded (Informed Search, slide 36). */
export const EIGHT_PUZZLE_COSTS: readonly {
	depth: number;
	ids: string;
	astarH1: number;
	astarH2: number;
}[] = [
	{ depth: 12, ids: '3,644,035', astarH1: 227, astarH2: 73 },
	{ depth: 24, ids: '≈ 54,000,000,000', astarH1: 39_135, astarH2: 1_641 }
];

/** Group digits: 1234567n → "1,234,567". */
export function formatCount(n: bigint | number): string {
	const s = (typeof n === 'bigint' ? n : BigInt(Math.round(n))).toString();
	const neg = s.startsWith('-');
	const digits = neg ? s.slice(1) : s;
	const grouped = digits.replace(/\B(?=(\d{3})+(?!\d))/g, ',');
	return neg ? `-${grouped}` : grouped;
}

/**
 * A large count in scientific form when it has more than `maxDigits` digits:
 * "1.2 × 10²⁵", the mantissa rounded to three significant digits.
 */
export function formatLarge(n: bigint, maxDigits = 15): string {
	const s = n.toString();
	if (s.length <= maxDigits || n < 0n) return formatCount(n);
	let exp = s.length - 1;
	// Three significant digits, rounded half up (999.5 → 1000 carries into the exponent).
	let head = Number(s.slice(0, 3)) + (Number(s[3] ?? '0') >= 5 ? 1 : 0);
	if (head === 1000) {
		head = 100;
		exp++;
	}
	const digits = String(head);
	const mantissa = `${digits[0]}.${digits.slice(1)}`.replace(/\.?0+$/, '');
	return `${mantissa} × 10${superscript(exp)}`;
}

const SUPERSCRIPT_DIGITS = '⁰¹²³⁴⁵⁶⁷⁸⁹';

/** 25 → "²⁵". */
export function superscript(n: number): string {
	return String(n)
		.split('')
		.map((c) => (c === '-' ? '⁻' : SUPERSCRIPT_DIGITS[Number(c)]))
		.join('');
}
